version: "3"
services:
    api:
        build:
            context: .
            dockerfile: src/WebApi/Dockerfile
            args:
                version: 1
        image: inmetrics-challenge-webapi
        ports:
            - 8080:80
        networks:
            - inmetrics-challenge-webapi
    prometheus:
        build:
            context: ./prometheus
            dockerfile: Dockerfile
            args:
                version: 1
        image: prometheus-local
        restart: always
        ports: 
            - 9090:9090
        networks:
            - inmetrics-challenge-webapi
        volumes: 
            - './prometheus/data:/data'
    grafana:
        build:
            context: ./grafana
            dockerfile: Dockerfile
            args:
                version: 1
        image: grafana-local
        restart: always
        ports:
            - 3000:3000
        networks: 
            - inmetrics-challenge-webapi  
networks:
  inmetrics-challenge-webapi:
    driver: overlay
    attachable: true